@url = http://localhost:8000
@blockchain = chain2
@stream = apistream

###
# Get list of streams
GET {{url}}/api/blockchain/{{blockchain}}/stream
Accept: application/json

###
# Get info for stream {stream} on blockchain {blockchain}
GET {{url}}/api/blockchain/{{blockchain}}/stream/{{stream}}
Accept: application/json

###
# Create new stream
POST {{url}}/api/blockchain/{{blockchain}}/stream
Accept: application/json
content-type: application/json

{
    "name": "mystream",
    "open": true
}
